<b> NumPy (Numeric Python) </b>

<b> Python Array </b>

In [1]:
import array
my_array = array.array("i",[1,2,3,4])

Type code	C Type	Python Type	Minimum size in bytes
'b'	signed char	int	1
'B'	unsigned char	int	1
'u'	Py_UNICODE	Unicode character	2 (see note)
'h'	signed short	int	2
'H'	unsigned short	int	2
'i'	signed int	int	2
'I'	unsigned int	int	2
'l'	signed long	int	4
'L'	unsigned long	int	4
'f'	float	float	4
'd'	double	float	8

In [2]:
my_array

array('i', [1, 2, 3, 4])

In [3]:
type(my_array)

array.array

In [4]:
my_array = array.array('f',[1.2,2.5,3.2,4.0])

In [5]:
my_array

array('f', [1.2000000476837158, 2.5, 3.200000047683716, 4.0])

<b> NumPy Array </b>

In [7]:
import numpy as np 

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [79]:
type(arr)

numpy.ndarray

A structured data type containing a 16-character string (in field ‘name’) and a sub-array of two 64-bit floating-point number (in field ‘grades’):

In [86]:
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (5,))])
# (5,) ==> reps shape of the array.

In [87]:
dt

dtype([('name', '<U16'), ('grades', '<f8', (5,))])

In [88]:
dt['name']

dtype('<U16')

In [89]:
dt['grades']

dtype(('<f8', (5,)))

In [90]:
x = np.array([('Sarah', (8.0, 7.0, 6.0, 7.0, 6.0)), ('John', (6.0, 7.0, 6.0, 7.0, 6.0))], dtype=dt)

In [91]:
x

array([('Sarah', [8., 7., 6., 7., 6.]), ('John', [6., 7., 6., 7., 6.])],
      dtype=[('name', '<U16'), ('grades', '<f8', (5,))])

In [92]:
arr = np.array((1,2,3))

In [93]:
arr

array([1, 2, 3])

In [94]:
type(arr)

numpy.ndarray

In [95]:
# Zero dimensional array 
zero_arr = np.array(50)

In [96]:
print(zero_arr)

50


In [97]:
type(zero_arr)

numpy.ndarray

In [98]:
#one dimensional array 
one_arr = np.array([1,2,3,4])

In [99]:
one_arr


array([1, 2, 3, 4])

In [100]:
type(one_arr)

numpy.ndarray

In [101]:
#2D array 
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr)

[[1 2 3]
 [4 5 6]]


In [104]:
float_list = [1.2,1.3,2.4,5.6]
my_np_float_array = np.array(float_list)
my_np_float_array

array([1.2, 1.3, 2.4, 5.6])

In [105]:
type(my_np_float_array)

numpy.ndarray

In [106]:
mixed_element_list = [1,1.2,2,2.5,7]
my_mixed_array = np.array(mixed_element_list)
my_mixed_array

array([1. , 1.2, 2. , 2.5, 7. ])

In [107]:
mixed_element_list = [1,1.2,2,2.5,7,'a','s']
my_mixed_Array = np.array(mixed_element_list)

In [108]:
my_mixed_Array

array(['1', '1.2', '2', '2.5', '7', 'a', 's'], dtype='<U32')

In [146]:
mxxint_list = mxxx_list = [1,3,4,8,56]
my_np_mxxint_array = np.array(mxxint_list, dtype='int32')
# int32
my_np_mxxint_array

array([ 1,  3,  4,  8, 56])

In [147]:
mxxx_list = [1,3,4,8,56, 'aaaa', 's']
my_np_mxx_array = np.array(mxxx_list, dtype='<U1')
my_np_mxx_array
# unicode of byte 1, so the value gets trimmed.

array(['1', '3', '4', '8', '5', 'a', 's'], dtype='<U1')

array([ 1,  3,  4,  8, 56])

In [148]:
my_int_list= [1,2,3,4,5]
my_np_array = np.array(my_int_list)
my_np_array


array([1, 2, 3, 4, 5])

In [149]:
to_back_list = my_np_array.tolist()

In [150]:
to_back_list

[1, 2, 3, 4, 5]

In [151]:
type(to_back_list)

list

<b> Properties of NumPy array </b> 

In [152]:
my_np_array

array([1, 2, 3, 4, 5])

In [141]:
type(my_np_array)

numpy.ndarray

In [153]:
my_np_array.dtype

dtype('int32')

In [154]:
my_np_float_array.dtype

dtype('float64')

In [155]:
my_np_array.ndim

1

In [156]:
my_np_array.shape

(5,)

In [157]:
my_np_array.size

5

<b> Prepopulated arrays </b>

In [158]:
zeros = np.zeros(6)

In [159]:
zeros

array([0., 0., 0., 0., 0., 0.])

In [160]:
zeros.dtype

dtype('float64')

In [161]:
zeros_ints = np.zeros(5,int)
zeros_ints

array([0, 0, 0, 0, 0])

In [164]:
ones = np.ones(3, int)

In [171]:
ones

array([1, 1, 1])

In [180]:
np.empty(10)

array([8., 7., 6., 7., 6., 6., 7., 6., 7., 6.])

In [173]:
np.empty(10, int)

array([         0, 1072693248,  858993459, 1072902963,          0,
       1073741824,          0, 1074003968,          0, 1075576832])

In [181]:
arange_array = np.arange(1,10)

In [182]:
arange_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
a1 = np.arange(5,50,5)

In [184]:
a1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [185]:
np.arange(1,11,1) 
# 2nd arg is not the included in the elements.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<b> 2D Array </b> 

In [186]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

two_d_array = np.array([l1,l2,l3])
two_d_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [187]:
l1 = [1,2,3]
l2 = [4,5,9]
a2 = np.array([l1,l2])

In [188]:
a2

array([[1, 2, 3],
       [4, 5, 9]])

In [189]:
two_d_array.dtype

dtype('int32')

In [190]:
two_d_array.ndim

2

In [191]:
two_d_array.size

9

In [192]:
two_d_array.shape

(3, 3)

<b> NumPy Computation </b> 

In [194]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
l1

[1, 2, 3, 4, 5]

In [195]:
a1

array([1, 2, 3, 4, 5])

In [196]:
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)

In [197]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> Ways to access the array elements </b>

In [198]:
a1

array([1, 2, 3, 4, 5])

In [199]:
a1[0]

1

In [200]:
a1[2]

3

In [201]:
a1[-1]

5

In [203]:
a1

array([1, 2, 3, 4, 5])

In [204]:
a1[3] = 4444
a1

array([   1,    2,    3, 4444,    5])

In [205]:
a1[:]

array([   1,    2,    3, 4444,    5])

In [206]:
a1[:2]

array([1, 2])

In [207]:
a1[3:]

array([4444,    5])

In [208]:
a1[1:3]

array([2, 3])

In [225]:
a1[-2:-4] # this will be empty coz -ve means order is changed!

array([], dtype=int32)

In [233]:
a1[-4:-2]

array([2, 3])

In [235]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [236]:
a2[0][0]

1

In [237]:
a2[1][2]

6

In [242]:
a2[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
a2[1:,:]

array([[4, 5, 6]])

In [245]:
a2[1:,1:]

array([[5, 6]])

In [246]:
a2[0,0]

1

In [247]:
a1

array([   1,    2,    3, 4444,    5])

In [248]:
a_sub = a1[:3]
a_sub

array([1, 2, 3])

In [249]:
a_sub[0] = 35

In [250]:
a_sub

array([35,  2,  3])

In [252]:
a1
# note the change in a_sub element affects the parent!

array([  35,    2,    3, 4444,    5])

In [253]:
a_sub_view = a1.view()

In [254]:
a_sub_view

array([  35,    2,    3, 4444,    5])

In [255]:
a1[0] = 100 

In [256]:
a1

array([ 100,    2,    3, 4444,    5])

In [258]:
a_sub_view
# change in the parent elements affect the views!

array([ 100,    2,    3, 4444,    5])

In [261]:
a_sub_view[2] = 2
# also the viceversa!!

In [262]:
a1

array([ 100,    2,    2, 4444,    5])

In [263]:
a_copy = a1.copy()

In [264]:
a_copy


array([ 100,    2,    2, 4444,    5])

In [96]:
a_copy[0] = 200

In [265]:
a_copy

array([ 100,    2,    2, 4444,    5])

In [266]:
a1
# but making a copy does not!!!

array([ 100,    2,    2, 4444,    5])

<b> Reshaping <b> 

In [267]:
a1
print("a1 ===> " , a1)
print(a1.shape)
print(a1.ndim)

a1 ===>  [ 100    2    2 4444    5]
(5,)
1


In [268]:
a1_reshaped = a1.reshape(5,1)
print("a1_shaped ==> ", a1_reshaped)
print("\n", a1_reshaped.shape)
print("\n", a1_reshaped.ndim)

a1_shaped ==>  [[ 100]
 [   2]
 [   2]
 [4444]
 [   5]]

 (5, 1)

 2


In [275]:
a1_reshaped.ndim

2

In [269]:
a1

array([ 100,    2,    2, 4444,    5])

In [270]:
one_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [277]:
two_Arr = one_arr.reshape(3,4)

In [278]:
two_Arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<b> Computation - Arit <b> 

In [279]:
a1

array([ 100,    2,    2, 4444,    5])

In [109]:
sum(a1)

4554

In [280]:
sum(two_Arr)

array([15, 18, 21, 24])

In [110]:
a11 = np.random.randint(1,100,size=1000)
a11.size

1000

In [111]:
a11

array([61, 36, 62, 23, 16, 29, 96, 17, 78, 46, 85, 56, 67, 28, 12, 29, 74,
       91, 47, 91, 62, 44, 93, 11, 26, 33, 21, 26, 10,  3, 58, 69, 27, 35,
       13, 35, 72, 65, 36, 44, 79, 13, 85, 54, 18, 90, 90, 44, 49, 79, 99,
       94, 86, 55, 78, 46, 87, 76, 56, 18, 57, 74, 32, 81, 79, 96, 28, 29,
       83, 55, 48, 30, 69, 27,  8, 37, 79, 88, 93,  9, 12, 46, 49,  6,  1,
       52, 38, 74, 61,  2, 19, 27, 90, 97, 87, 65, 38, 36, 57, 55, 42, 11,
       69,  3, 75,  6, 42,  7, 61, 15, 77, 19, 97, 86, 62, 62, 64, 26, 53,
       19, 17, 88, 55,  3, 71,  4, 45, 40,  4, 59,  9, 34,  7,  6, 45, 13,
       55, 96,  6, 35, 60, 83, 37,  8, 88, 13, 99, 46, 46,  8, 20, 12, 48,
       38, 16, 39, 31, 57, 56, 74, 64, 65, 83, 15, 74, 37, 12, 30, 31, 45,
       40, 61, 36, 79, 25, 85, 59, 59,  3, 22, 53, 66, 59, 80, 72, 53, 68,
       97, 47,  4, 65, 74, 68, 46, 15, 45,  9, 27, 85, 61, 80, 60, 45, 28,
       45, 77, 67, 56, 11, 78, 83, 67, 25, 31, 59, 72, 67, 59, 63, 48, 16,
       81,  2,  5, 37, 36

In [112]:
sum(a11)

49816

In [113]:
np.sum(a11)

49816

In [114]:
%timeit sum(a11)

180 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [115]:
%timeit np.sum(a11)

4.85 µs ± 130 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [116]:
a1

array([ 100,    2,    3, 4444,    5])

In [117]:
a1 + 5 

array([ 105,    7,    8, 4449,   10])

In [118]:
a1 ** 2

array([   10000,        4,        9, 19749136,       25], dtype=int32)

In [119]:
np.add(a1,5)

array([ 105,    7,    8, 4449,   10])

In [120]:
np.power(a1,2)

array([   10000,        4,        9, 19749136,       25], dtype=int32)

In [121]:

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
a2 + 3 

array([[4, 5, 6],
       [7, 8, 9]])

In [123]:
a2 - 5

array([[-4, -3, -2],
       [-1,  0,  1]])

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.sum(a2,axis=0)

array([5, 7, 9])

In [127]:
np.sum(a2,axis=1)

array([ 6, 15])

<b> Comparisons </b>

In [128]:
a1

array([ 100,    2,    3, 4444,    5])

In [129]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [281]:
type(a2)

numpy.ndarray

In [282]:
a1 

array([ 100,    2,    2, 4444,    5])

In [283]:
a1 == 5

array([False, False, False, False,  True])

In [284]:
a1 != 45

array([ True,  True,  True,  True,  True])

In [285]:
a1

array([ 100,    2,    2, 4444,    5])

In [286]:
(a1 < 500)

array([ True,  True,  True, False,  True])

In [287]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [288]:
np.sum(a2 < 100)

6

In [289]:
(a2 < 100)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [290]:
#np.greater(a1,5)

a1 > 5 

array([ True, False, False,  True, False])

In [291]:
# Aggregations 

a1

array([ 100,    2,    2, 4444,    5])

In [292]:
a1.sum()

4553

In [294]:
sum(a1)

4553

In [295]:
np.sum(a1)

4553

In [296]:
a1.max()

4444

In [297]:
a1.min()

2

In [298]:

a1.mean()

910.6

In [299]:
a1.std()


1767.0997255389973

In [300]:
a1.var()

3122641.44

In [301]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [302]:
a2.min()

1

In [303]:
a2.max()

6

In [305]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [307]:
np.sum(a2,axis=0)

array([5, 7, 9])

In [308]:
np.sum(a2,axis=1)

array([ 6, 15])

In [156]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [310]:
arr3 = np.array([[[1, 2, 3],
       [4, 5, 6]],[[1, 2, 3],
       [4, 5, 6]],[[1, 2, 3],
       [4, 5, 6]]])

In [312]:
arr3.shape

(3, 2, 3)

In [316]:
x = np.sum(arr3, axis=0)
y = np.sum(arr3, axis=1)
z = np.sum(arr3, axis=2)

In [317]:
np.min(a2,axis=1)

array([1, 4])

In [318]:
np.any(a1>5)

True

In [321]:
a1

array([ 100,    2,    2, 4444,    5])

In [324]:
np.any((a1>5555) | (a1 < 3))

True

In [162]:
a1

array([ 100,    2,    3, 4444,    5])

In [164]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

<b> Linear Algebra </b>

In [325]:
X = np.array([[1,2],[3,4]])
print(X)


[[1 2]
 [3 4]]


In [326]:
X.transpose()
# (2x,2y) ==> (2y,2x)

array([[1, 3],
       [2, 4]])

In [327]:
x = np.eye(3)

In [328]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [329]:
#Fruit seller .... Wed : 20 mangoes and 10oranges ... Rs 350 

# Thursday 17 mangoes and 22 oranges ..... Rs. 500 

# both days price of the fruits dint change , what is the price of each fruits ? 

In [330]:
# x --> mangoes 
# y --> orange 

#20x + 10y = 350 
#17x + 22y = 500 

In [333]:
A = np.array([[20,10],[17,22]])
B = np.array([350,500])
X = np.linalg.solve(A,B)
print(X)

[10. 15.]


In [334]:
A

array([[20, 10],
       [17, 22]])

In [335]:
B

array([350, 500])

In [336]:
X = np.linalg.solve(A,B)

In [338]:
X

array([10., 15.])