In [1]:
import numpy as np

In [2]:
mixed = [1,2,3.2,"as",23.3]
mixed_np = np.array(mixed)

In [8]:
mixed_np.dtype

dtype('<U32')

In [5]:
bac_to_list = mixed_np.tolist()

In [9]:
bac_to_list

['1', '2', '3.2', 'as', '23.3']

In [12]:
np.ndarray([1,2,3,4], dtype=int)

array([[[[       110,        112,         46,        110],
         [       100,         97,        114,        114],
         [        97,        121,         40,         91]],

        [[        49,         44,         50,         44],
         [        51,         44,         93,         41],
         [        10,  959590708,  959866160, 1664300336]]]])

In [16]:
x = np.array([[1, 2], [3, 4]])
x.shape

(2, 2)

In [17]:
y = np.array([[5, 6]])
y.shape

(1, 2)

In [20]:
z = np.concatenate((x, y), axis=0)
z.shape

(3, 2)

In [21]:
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
v = np.array([[5],
[6]])

In [26]:
w = np.concatenate((x, v), axis=1)
w.shape

(2, 3)

In [27]:
w

array([[1, 2, 5],
       [3, 4, 6]])

In [28]:
w.reshape(1,6)

array([[1, 2, 5, 3, 4, 6]])

In [29]:
w.reshape(3,2)

array([[1, 2],
       [5, 3],
       [4, 6]])

In [30]:
z.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

In [32]:
# 3,2,4
array_example.shape

(3, 2, 4)

In [33]:
array_example.ndim

3

In [34]:
array_example.size

24

In [35]:
A = np.array([[20,10],
[17,22]])
B = np.array([350,400])
X = np.linalg.solve(A,B)

In [36]:
x

array([[1, 2],
       [3, 4]])