In [55]:
from math import ceil, floor, pow
import numpy as np

In [56]:
def Round_off(N, n):
    b = N
    c = floor(N)
    i = 0;
    while(b >= 1):
        b = b / 10
        i = i + 1
    d = n - i
    b = N
    b = b * pow(10, d)
    e = b + 0.5
    if (float(e) == float(ceil(b))):
        f = (ceil(b))
        h = f - 2
        if (h % 2 != 0):
            e = e - 1
    j = floor(e)
    m = pow(10, d)
    j = j / m
    return j

In [57]:
def generate_diagonal_dominant_system(order_of_matrix):
    LHS_Coefficients = np.random.randn(order_of_matrix,order_of_matrix)
    flag=1
    RHS_Coefficients = np.random.randn(order_of_matrix,1)
    num_rows, num_cols = LHS_Coefficients.shape
    for i in range(num_rows):
        ele=abs(LHS_Coefficients[i][i])
        su=0
        for j in range(num_cols):
            if i!= j:
                su=su+abs(LHS_Coefficients[i][j])
        if ele <= su:
            flag=0
            break
    if flag == 1:
        return np.column_stack((LHS_Coefficients,RHS_Coefficients))
    else:
        flag=1
        return generate_diagonal_dominant_system(order_of_matrix)


In [58]:
def gauss_siedel(Augumented_matrix):
    num_rows, num_cols = Augumented_matrix.shape
    solution=np.arange(num_rows)
    solution.fill(0)
    newsolution=np.arange(num_rows)
    newsolution.fill(0)
    solution=np.array((solution),dtype=float)
    newsolution=np.array((newsolution),dtype=float)
    Augumented_matrix=np.array((Augumented_matrix),dtype=float)
    intermediate_matrix= Augumented_matrix.copy()
    
    for i in range(num_rows):
        Augumented_matrix[i][num_cols-1]=Round_off((Augumented_matrix[i][num_cols-1]/intermediate_matrix[i][i]),8)
        newsolution[i]=solution[i]
        for j in range(num_cols):
            if j!=num_cols-1:
                Augumented_matrix[i][j]=Round_off((Augumented_matrix[i][j]/intermediate_matrix[i][i]),8)
    counter = 0
    while True:
        for i in range(num_rows):
            solution[i]=newsolution[i]
            #newsolution[i]=Augumented_matrix[i][num_cols-1]
        for i in range(num_rows):
            su=0
            for j in range(num_cols):
                if j!=i and j!=num_cols-1:
                    su=su+Augumented_matrix[i][j] * newsolution[j]
            newsolution[i]=Augumented_matrix[i][num_cols-1]-su
            newsolution[i]=Round_off(newsolution[i],8)
        counter=counter+1
        print("**********************The values of Iteration ",counter, " is ",newsolution)
        if np.allclose(solution, newsolution, rtol=0.01):
            break
    Augumented_matrix=intermediate_matrix.copy()

In [59]:
def gauss_jacobi(Augumented_matrix):
    num_rows, num_cols = Augumented_matrix.shape
    solution=np.arange(num_rows)
    solution.fill(0)
    newsolution=np.arange(num_rows)
    newsolution.fill(0)
    solution=np.array((solution),dtype=float)
    newsolution=np.array((newsolution),dtype=float)
    Augumented_matrix=np.array((Augumented_matrix),dtype=float)
    intermediate_matrix= Augumented_matrix.copy()
    
    for i in range(num_rows):
        Augumented_matrix[i][num_cols-1]=Round_off((Augumented_matrix[i][num_cols-1]/intermediate_matrix[i][i]),8)
        newsolution[i]=solution[i]
        for j in range(num_cols):
            if j!=num_cols-1:
                Augumented_matrix[i][j]=Round_off((Augumented_matrix[i][j]/intermediate_matrix[i][i]),8)
    counter = 0
    while True:
        for i in range(num_rows):
            solution[i]=newsolution[i]
            #newsolution[i]=Augumented_matrix[i][num_cols-1]
        for i in range(num_rows):
            su=0
            for j in range(num_cols):
                if j!=i and j!=num_cols-1:
                    su=su+Augumented_matrix[i][j] * solution[j]
            newsolution[i]=Augumented_matrix[i][num_cols-1]-su
            newsolution[i]=Round_off(newsolution[i],8)
        counter=counter+1
        print("**********************The values of Iteration ",counter, " is ",newsolution)
        if np.allclose(solution, newsolution, rtol=0.01):
            break
    Augumented_matrix=intermediate_matrix.copy()
        
    

In [60]:
Augumented_matrix=generate_diagonal_dominant_system(3)
print(Augumented_matrix)

[[-1.29886386  0.51414005 -0.67913213 -0.76742221]
 [ 0.04287619 -2.17604238 -1.02432169  0.44001125]
 [ 0.32662121  0.32654054  1.36795564 -0.68851777]]


In [61]:
#Augumented_matrix[0][0]=-0.9815
#Augumented_matrix[0][1]=0.0661
#Augumented_matrix[0][2]=0.3732
#Augumented_matrix[0][3]=0.15291635
#Augumented_matrix[1][0]=0.2709
#Augumented_matrix[1][1]=-1.152
#Augumented_matrix[1][2]=0.2068
#Augumented_matrix[1][3]=0.98563742
#Augumented_matrix[2][0]=0.3125
#Augumented_matrix[2][1]=-0.4523
#Augumented_matrix[2][2]=-1.2511
#Augumented_matrix[2][3]=0.58006576


#Augumented_matrix[0][0]=0.0004
#Augumented_matrix[0][1]=1.402
#Augumented_matrix[1][0]=0.4003
#Augumented_matrix[1][1]=-1.502
#Augumented_matrix[0][2]=1.406
#Augumented_matrix[1][2]=2.501
gauss_jacobi(Augumented_matrix)

**********************The values of Iteration  1  is  [ 0.59084114 -0.20220711 -0.50331879]
**********************The values of Iteration  2  is  [ 0.77396826  0.04636037 -0.59612328]
**********************The values of Iteration  3  is  [ 0.92088512  0.09365423 -0.69918259]
**********************The values of Iteration  4  is  [ 0.99349208  0.14506183 -0.74555071]
**********************The values of Iteration  5  is  [ 1.0380855   0.16831918 -0.77515813]
**********************The values of Iteration  6  is  [ 1.0627724   0.18313485 -0.79135721]
**********************The values of Iteration  7  is  [ 1.0771069   0.19124662 -0.80078821]
**********************The values of Iteration  8  is  [ 1.085249    0.19596849 -0.80614713]
**********************The values of Iteration  9  is  [ 1.0899201   0.1986515  -0.80921833]
**********************The values of Iteration  10  is  [ 1.092588    0.20018924 -0.81097408]


In [62]:
#Augumented_matrix[0][0]=-0.9815
#Augumented_matrix[0][1]=0.0661
#Augumented_matrix[0][2]=0.3732
#Augumented_matrix[0][3]=0.15291635
#Augumented_matrix[1][0]=0.2709
#Augumented_matrix[1][1]=-1.152
#Augumented_matrix[1][2]=0.2068
#Augumented_matrix[1][3]=0.98563742
#Augumented_matrix[2][0]=0.3125
#Augumented_matrix[2][1]=-0.4523
#Augumented_matrix[2][2]=-1.2511
#Augumented_matrix[2][3]=0.58006576
gauss_siedel(Augumented_matrix)

**********************The values of Iteration  1  is  [ 0.59084114 -0.19056532 -0.59890226]
**********************The values of Iteration  2  is  [ 0.8285539   0.09603791 -0.72407416]
**********************The values of Iteration  3  is  [ 1.0074506   0.15848463 -0.78169507]
**********************The values of Iteration  4  is  [ 1.0622974   0.18668903 -0.8015232 ]
**********************The values of Iteration  5  is  [ 1.0838293   0.19644692 -0.80899356]
**********************The values of Iteration  6  is  [ 1.0915978   0.20011649 -0.81172437]
**********************The values of Iteration  7  is  [ 1.0944782   0.20145871 -0.8127325 ]
