# MFDS Assignment-1

<p><b>Q1)</b> Write a code to perform Gauss elimination with and without pivotingfor a 2 x 2 system, taking the number of significant     digits (d) to be consideredas user input. Using the code, solve the 2 x 2 system with random coefficientsford= 3,4,5 and 6.  Display the results in a tabular form.
</p>
<p><b>Q2)</b> Write a code to perform
    a)  Gauss Jacobi method
    b)  Gauss Seidel method
for a 3 x 3 system by checking the convergence criteria using a suitable norm.Test the method on a random 3 x 3 system, which is diagonally dominantand check your results.  A comparison between the two methods should bepresented in tabular form.  The stopping criteria could be taken as the low-est iteration number when the relative percentage error is less than 1%.

Generate a random matrix of size 3 x 3 which cannot be made diagonallydominant and check if the iterates converge.  The random entries generatedshould be of the form n.dddd</p>

### Q1. Write a code to perform Gauss elimination with and without pivotingfor a 2 x 2 system, 
### taking the number of significant digits (d) to be considered as user input. 
### Using the code, solve the 2 x 2 system with random coefficients for d= 3,4,5 and 6.  
### Display the results in a tabular form.

In [1]:
import numpy as np

In [2]:
A = np.random.randn(2,2)
f = np.random.randn(2,1)

In [5]:
def sig_round_off(number,digits):
    return np.round(number+5*10**(-1*(digits+1)),decimals=digits-1)

In [6]:
def Cal_LU(D,g,d):
    A= np.array((D),dtype=float)
    f= np.array((g),dtype=float)
    n = f.size
    for i in range(0,n-1):     # Loop through the columns of the matrix
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            if A[i,i] == 0:
                print("Error: Zero on diagonal!")
                print("Need algorithm with pivoting")
                break
            m = A[j,i]/A[i,i]
            m = sig_round_off(m,d)
            print("ratio:",m)
            A[j,:] = sig_round_off(A[j,:] - m*A[i,:],d)
            f[j] = sig_round_off(f[j] - m*f[i],d)
    return A,f

In [7]:
def Cal_LU_pivot(D,g,d):
    A= np.array((D),dtype=float)
    f= np.array((g),dtype=float)
    n = len(f)
    for i in range(0,n-1):     # Loop through the columns of the matrix
        
        for k in range(i+1,n):
            if np.abs(A[k,i])>np.abs(A[i,i]):
                A[[i,k]]=A[[k,i]]             # Swaps ith and kth rows to each other
                f[[i,k]]=f[[k,i]]
                
        for j in range(i+1,n):     # Loop through rows below diagonal for each column
            m = A[j,i]/A[i,i]
            m = sig_round_off(m,d)
            print("ratio:",m)
            A[j,:] = sig_round_off(A[j,:] - m*A[i,:],d)
            f[j] = sig_round_off(f[j] - m*f[i],d)
    return A,f

In [ ]:
[A1 0.00x
 0.00x A2][x1
     x2] = [f1
           f2]

In [40]:
A = np.random.randn(2,2)
f = np.random.randn(2,1)

In [42]:
n = f.size

In [44]:
X = np.zeros(n)

In [46]:
f

array([[0.59641206],
       [1.07642824]])

In [47]:
f[n-1]

array([1.07642824])

In [8]:
def Back_Subs(A,f,d):
    n = f.size
    x = np.zeros(n)             # Initialize the solution vector, x, to zero
    x[n-1] = f[n-1]/A[n-1,n-1]    # Solve for last entry first
    for i in range(n-2,-1,-1):      # Loop from the end to the beginning
        sum_ = 0
        for j in range(i+1,n):        # For known x values, sum and move to rhs
            sum_ = sig_round_off(sum_ + A[i,j]*x[j],d)
        x[i] = sig_round_off((f[i] - sum_)/A[i,i],d)
    return x

In [9]:
def gauss_elimination_without_pivot(A,f,D):
    print("System of equations:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), f[i]))
    B,g = Cal_LU(A,f,D)
    X = Back_Subs(B,g,D)
    return A,f,X

In [10]:
def gauss_elimination_with_pivot(A,f,D):
    print("System of equations:")
    for i in range(A.shape[0]):
        row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
        print("[{}] = [{}]".format(" + ".join(row), f[i]))
    B,g = Cal_LU_pivot(A,f,D)
    X = Back_Subs(B,g,D)
    return A,f,X

In [11]:
gauss_elimination_without_pivot(A,f,3)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 1.74


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.93      , 4.61538462]))

In [12]:
gauss_elimination_with_pivot(A,f,3)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 0.58


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.73 , 4.375]))

In [13]:
gauss_elimination_without_pivot(A,f,4)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 1.738


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.863     , 4.51698113]))

In [14]:
gauss_elimination_with_pivot(A,f,4)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 0.575


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.87      , 4.52631579]))

In [15]:
gauss_elimination_without_pivot(A,f,5)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 1.7384


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.8695    , 4.52627599]))

In [16]:
gauss_elimination_with_pivot(A,f,5)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 0.5752


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.8705    , 4.52728468]))

In [17]:
gauss_elimination_without_pivot(A,f,6)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 1.73844


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.8693    , 4.52599146]))

In [18]:
gauss_elimination_with_pivot(A,f,6)

System of equations:
[0.8358597365210578*x1 + -0.6050215391320647*x2] = [[-0.33998983]]
[1.4530902543916977*x1 + -1.3163070077115926*x2] = [[-1.78822558]]
ratio: 0.57523


(array([[ 0.83585974, -0.60502154],
        [ 1.45309025, -1.31630701]]),
 array([[-0.33998983],
        [-1.78822558]]),
 array([2.86916   , 4.52582808]))

In [38]:
A = np.array([[4.03,2.16],[6.21,3.35]])
f = np.array([[-4.61],[-7.19]])

In [39]:
gauss_elimination_with_pivot(A,f,4)

System of equations:
[4.03*x1 + 2.16*x2] = [[-4.61]]
[6.21*x1 + 3.35*x2] = [[-7.19]]
ratio: 0.649


(array([[4.03, 2.16],
        [6.21, 3.35]]),
 array([[-4.61],
        [-7.19]]),
 array([ 1., -4.]))

### Write a code to perform
### a)  Gauss Jacobi method
### b)  Gauss Seidel method
### for a 3 x 3 system by checking the convergence criteria using a suitable norm.
### Test the method on a random 3 x 3 system, which is diagonally dominantand check your results.  
### A comparison between the two methods should bepresented in tabular form.  
### The stopping criteria could be taken as the low-est iteration number when the relative percentage error is less than 1%.

In [21]:
def generate_matrix():
    return np.around(np.random.randn(3,3),4)

In [22]:
def lu(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U

In [23]:
def generate_diagonally_dominant_matrix():
    A = generate_matrix()
    D = np.diag(np.abs(A)) # Find diagonal coefficients
    S = np.sum(np.abs(A), axis=1) - D # Find row sum without diagonal
    L,U = lu(A)
    C = -np.linalg.inv(np.identity(3)+L)*U
    if np.all(D > S) and np.linalg.norm(C,'fro') < 1:
        return A
    else:
        return generate_diagonally_dominant_matrix()

In [24]:
A = generate_diagonally_dominant_matrix()

In [26]:
#Test for convergence:
L,U = lu(A)
C = -np.linalg.inv(np.identity(3)+L)*U
np.linalg.norm(C,'fro') < 1

True

In [27]:
b = np.random.rand(3,1)

In [51]:
b = np.array([[0.5715734 ],
       [0.15102973],
       [0.27120801]])

### a) Gauss Jacobi Method

In [29]:

ITERATION_LIMIT = 1000

# prints the system
print("System:")
for i in range(A.shape[0]):
    row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
    print(" + ".join(row), "=", b[i])
print()

x = np.zeros_like(b)
for it_count in range(ITERATION_LIMIT):
    if it_count != 0:
        print("Iteration {0}: {1}".format(it_count, x))
    x_new = np.zeros_like(x)

    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x[:i])
        s2 = np.dot(A[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if x_new[i] == x_new[i-1]:
            break

    if np.allclose(x, x_new, atol=0.01, rtol=0.):
        break

    x = x_new

print("Solution:")
print(x)
error = np.dot(A, x) - b
print("Error:")
print(error)

System:
-1.6652*x1 + 0.6023*x2 + 0.8628*x3 = [0.5715734]
-0.4416*x1 + 0.9493*x2 + 0.0492*x3 = [0.15102973]
0.5502*x1 + 0.6113*x2 + -1.1992*x3 = [0.27120801]

Iteration 1: [[-0.3432461 ]
 [ 0.15909589]
 [-0.22615744]]
Iteration 2: [[-0.40288169]
 [ 0.01114421]
 [-0.3025406 ]]
Iteration 3: [[-0.49597242]
 [-0.01263861]
 [-0.4053211 ]]
Iteration 4: [[-0.55782889]
 [-0.05061613]
 [-0.46015512]]
Iteration 5: [[-0.59997678]
 [-0.07654891]
 [-0.50789452]]
Iteration 6: [[-0.63409212]
 [-0.09368125]
 [-0.54045162]]
Iteration 7: [[-0.65715786]
 [-0.10786383]
 [-0.56483726]]
Iteration 8: [[-0.67492275]
 [-0.11732981]
 [-0.58264962]]
Iteration 9: [[-0.68757581]
 [-0.1246706 ]
 [-0.5956256 ]]
Solution:
[[-0.68757581]
 [-0.1246706 ]
 [-0.5956256 ]]
Error:
[[-0.01561703]
 [ 0.00494917]
 [-0.01144913]]


### b) Gauss-Seidel Method

In [30]:

ITERATION_LIMIT = 1000

print("System of equations:")
for i in range(A.shape[0]):
    row = ["{}*x{}".format(A[i, j], j + 1) for j in range(A.shape[1])]
    print("[{}] = [{}]".format(" + ".join(row), b[i]))

x = np.zeros_like(b)
for it_count in range(1, ITERATION_LIMIT):
    x_new = np.zeros_like(x)
    print("Iteration {0}: {1}".format(it_count, x))
    for i in range(A.shape[0]):
        s1 = np.dot(A[i, :i], x_new[:i])
        s2 = np.dot(A[i, i + 1 :], x[i + 1 :])
        x_new[i] = (b[i] - s1 - s2) / A[i, i]
    if np.allclose(x, x_new, rtol=0.01):
        break
    x = x_new

print("Solution: {0}".format(x))
error = np.dot(A, x) - b
print("Error: {0}".format(error))

System of equations:
[-1.6652*x1 + 0.6023*x2 + 0.8628*x3] = [[0.5715734]]
[-0.4416*x1 + 0.9493*x2 + 0.0492*x3] = [[0.15102973]]
[0.5502*x1 + 0.6113*x2 + -1.1992*x3] = [[0.27120801]]
Iteration 1: [[0.]
 [0.]
 [0.]]
Iteration 2: [[-0.3432461]
 [-0.000577 ]
 [-0.3839349]]
Iteration 3: [[-0.54238527]
 [-0.07331509]
 [-0.51237984]]
Iteration 4: [[-0.63524646]
 [-0.10985571]
 [-0.57361191]]
Iteration 5: [[-0.68018967]
 [-0.12758909]
 [-0.60327183]]
Iteration 6: [[-0.70197168]
 [-0.13618455]
 [-0.61764713]]
Iteration 7: [[-0.71252901]
 [-0.14035062]
 [-0.62461458]]
Iteration 8: [[-0.71764595]
 [-0.14236984]
 [-0.62799157]]
Solution: [[-0.71764595]
 [-0.14236984]
 [-0.62799157]]
Error: [[-0.00412984]
 [-0.00016615]
 [ 0.        ]]


### Generate a random matrix of size 3 x 3 which cannot be made diagonallydominant 
### and check if the iterates converge.  
### The random entries generatedshould be of the form n.dddd

In [31]:
def nondd():
    A = generate_matrix()
    D = np.diag(np.abs(A)) # Find diagonal coefficients
    S = np.sum(np.abs(A), axis=1) - D # Find row sum without diagonal
    if all(D < S):
        return A
    else:
        return nondd()

In [32]:
AA = nondd()

In [33]:
AA

array([[-0.3959, -1.0441,  1.2641],
       [-0.7188, -0.8932, -0.9533],
       [ 0.547 , -2.2368, -0.7379]])

In [34]:
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

In [35]:
if is_pos_def(AA):
    AA = nondd()

In [36]:
ITERATION_LIMIT = 1000

# prints the system
print("System:")
for i in range(AA.shape[0]):
    row = ["{}*x{}".format(AA[i, j], j + 1) for j in range(AA.shape[1])]
    print(" + ".join(row), "=", b[i])
print()

x = np.zeros_like(b)
for it_count in range(ITERATION_LIMIT):
    if it_count != 0:
        print("Iteration {0}: {1}".format(it_count, x))
    x_new = np.zeros_like(x)

    for i in range(AA.shape[0]):
        s1 = np.dot(AA[i, :i], x[:i])
        s2 = np.dot(AA[i, i + 1:], x[i + 1:])
        x_new[i] = (b[i] - s1 - s2) / AA[i, i]
        if x_new[i] == x_new[i-1]:
            break

    if np.allclose(x, x_new, atol=0.01, rtol=0.):
        break

    x = x_new

print("Solution:")
print(x)
error = np.dot(AA, x) - b
print("Error:")
print(error)

System:
-0.3959*x1 + -1.0441*x2 + 1.2641*x3 = [0.5715734]
-0.7188*x1 + -0.8932*x2 + -0.9533*x3 = [0.15102973]
0.547*x1 + -2.2368*x2 + -0.7379*x3 = [0.27120801]

Iteration 1: [[-1.44373174]
 [-0.16908836]
 [-0.36754033]]
Iteration 2: [[-2.17134621]
 [ 1.3850211 ]
 [-0.92520995]]
Iteration 3: [[-8.05059819]
 [ 2.56575971]
 [-6.17556523]]
Iteration 4: [[-27.92880809]
 [ 12.90070151]
 [-14.11299166]]
Iteration 5: [[-80.52899369]
 [ 37.36913622]
 [-60.17692799]]
Iteration 6: [[-292.14029604]
 [ 128.8623784 ]
 [-173.34035975]]
Iteration 7: [[-894.76214056]
 [ 419.93369908]
 [-607.55023439]]
Iteration 8: [[-3048.82192448]
 [ 1368.31799749]
 [-1936.59546958]]
Iteration 9: [[-9793.59112823]
 [ 4520.26268555]
 [-6408.22672106]]
Iteration 10: [[-32383.9788873 ]
 [ 14720.6054707 ]
 [-20962.58182707]]
Iteration 11: [[-105756.89677433]
 [  48433.81353583]
 [ -68629.02558101]]
Iteration 12: [[-346866.045777  ]
 [ 158354.18322664]
 [-225214.86361366]]
Iteration 13: [[-1136732.21362558]
 [  519507.9401

Iteration 206: [[-3.47206755e+105]
 [ 1.58646387e+105]
 [-2.25298972e+105]]
Iteration 207: [[-1.13776995e+106]
 [ 5.19872062e+105]
 [-7.38287482e+105]]
Iteration 208: [[-3.72838501e+106]
 [ 1.70358094e+106]
 [-2.41931155e+106]]
Iteration 209: [[-1.22176322e+107]
 [ 5.58250430e+106]
 [-7.92789870e+106]]
Iteration 210: [[-4.00362452e+107]
 [ 1.82934392e+107]
 [-2.59791170e+107]]
Iteration 211: [[-1.31195710e+108]
 [ 5.99461994e+107]
 [-8.51315772e+107]]
Iteration 212: [[-4.29918297e+108]
 [ 1.96439105e+108]
 [-2.78969660e+108]]
Iteration 213: [[-1.40880934e+109]
 [ 6.43715908e+108]
 [-9.14162216e+108]]
Iteration 214: [[-4.61656034e+109]
 [ 2.10940774e+109]
 [-2.99563959e+109]]
Iteration 215: [[-1.51281147e+110]
 [ 6.91236765e+109]
 [-9.81648155e+109]]
Iteration 216: [[-4.95736736e+110]
 [ 2.26512995e+110]
 [-3.21678584e+110]]
Iteration 217: [[-1.62449133e+111]
 [ 7.42265742e+110]
 [-1.05411609e+111]]
Iteration 218: [[-5.32333369e+111]
 [ 2.43234800e+111]
 [-3.45425771e+111]]
Iteration 21

Iteration 421: [[-2.32188832e+216]
 [ 1.06092173e+216]
 [-1.50664998e+216]]
Iteration 422: [[-7.60865022e+216]
 [ 3.47655928e+216]
 [-4.93717663e+216]]
Iteration 423: [[-2.49329642e+217]
 [ 1.13924186e+217]
 [-1.61787498e+217]]
Iteration 424: [[-8.17034146e+217]
 [ 3.73320833e+217]
 [-5.30165243e+217]]
Iteration 425: [[-2.67735834e+218]
 [ 1.22334379e+218]
 [-1.73731091e+218]]
Iteration 426: [[-8.77349827e+218]
 [ 4.00880392e+218]
 [-5.69303482e+218]]
Iteration 427: [[-2.87500821e+219]
 [ 1.31365435e+219]
 [-1.86556392e+219]]
Iteration 428: [[-9.42118175e+219]
 [ 4.30474472e+219]
 [-6.11331012e+219]]
Iteration 429: [[-3.08724912e+220]
 [ 1.41063188e+220]
 [-2.00328492e+220]]
Iteration 430: [[-1.01166790e+221]
 [ 4.62253267e+220]
 [-6.56461129e+220]]
Iteration 431: [[-3.31515824e+221]
 [ 1.51476856e+221]
 [-2.15117285e+221]]
Iteration 432: [[-1.08635197e+222]
 [ 4.96378059e+221]
 [-7.04922873e+221]]
Iteration 433: [[-3.55989223e+222]
 [ 1.62659289e+222]
 [-2.30997828e+222]]
Iteration 43

<ipython-input-36-47b5c1c5827e>:19: RuntimeWarning: overflow encountered in true_divide
  x_new[i] = (b[i] - s1 - s2) / AA[i, i]


### As the solution is <i>Inf</i> this shows the matrix AA doesn't converge. Also, as per the Jacobbi condition of Convergence of a matrix is:
<p><b> 1. The standard convergence condition (for any iterative method) is when the spectral radius of the iteration matrix is less than 1</b></p>
<p><b>2. A sufficient (but not necessary) condition for the method to converge is that the matrix A is strictly or irreducibly diagonally dominant.</b></p>
<p><b>3. In case that the system matrix A is of symmetric positive-definite type one can show convergence.</b></p>

The non diagonally dominant matrix AA above is not symmetric positive-definite type. This also shows that the matrix AA doesn't reduce to diagonally dominant.