> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [1]:
import jovian

In [2]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "prashanth-k-narasimhan/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations


'https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [3]:
import numpy as np

In [165]:
# List of functions explained 
function1 = np.matmul  # also comparison with np.dot
function2 = np.reshape # also ravel, order='F' 
function3 = np.extract
function4 = np.array_split
function5 = np.stack

## Function 1 - np.matmul

Matrix product of two arrays.

In [5]:
# Example 1 - a case of broadcasting
arr1 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
arr2 = np.array([4, 5, 6, 7])

In [6]:
arr1.shape

(3, 4)

In [7]:
arr2.shape

(4,)

In [8]:
arr1 + arr2

# array2 gets broadcasted to match array1.

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

A case where broadcasting in matrices is shown.

In [9]:
# Example 2 - working
arr5 = np.array([[7, 8],[7, 8],[7, 8]])
arr11 = np.array([[7, 8, 9]])

In [10]:
arr5.shape

(3, 2)

In [11]:
arr11.shape

(1, 3)

In [12]:
np.matmul(arr11, arr5)

array([[168, 192]])

In [13]:
np.matmul(arr5, arr11)
# the vice-versa case doesn't work. typical matrix multiplication. dimensions are not compatible!!

# ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

Matrix multiplication obeys the rule (n?,k),(k,m?)->(n?,m?) 

In [14]:
# Example 3 - compare mutmul with dot (with respect to broadcasting)
np.dot(arr11, arr5)

array([[168, 192]])

In [15]:
np.dot(arr5, arr11)
# does not work. shapes dont match!! but throws a diff error
# ValueError: shapes (3,2) and (1,3) not aligned: 2 (dim 1) != 1 (dim 0)

ValueError: shapes (3,2) and (1,3) not aligned: 2 (dim 1) != 1 (dim 0)

In [16]:
arr11 * arr5
# consider the dot product equivalent
# ValueError: operands could not be broadcast together with shapes (1,3) (3,2)
# Broadcasting failed!!

ValueError: operands could not be broadcast together with shapes (1,3) (3,2) 

In [17]:
# with proper broadcasting!!
arr1 * arr2

array([[ 4, 10, 18, 28],
       [20, 30, 42, 56],
       [36,  5, 12, 21]])

In [18]:
arr2 * arr1

array([[ 4, 10, 18, 28],
       [20, 30, 42, 56],
       [36,  5, 12, 21]])

comparing with matmul with dot and *, shows that they are not entirely the same.

matmul differs from dot in two important ways:

* Multiplication by scalars is not allowed, use * instead.

* Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature (n,k),(k,m)->(n,m):

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "prashanth-k-narasimhan/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations


'https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations'

## Function 2 - reshape

Gives a new shape to an array without changing its data.

In [29]:
# Example 1 - working
arr1 = np.arange(1,100,5)

In [30]:
arr1.reshape(2,2,5)

array([[[ 1,  6, 11, 16, 21],
        [26, 31, 36, 41, 46]],

       [[51, 56, 61, 66, 71],
        [76, 81, 86, 91, 96]]])

Reshape can change the dimension of the array, if the number of elements for both the arrays are equal.
arr1 ==> 20 elements ;
reshape ==> 2x2x5

In [34]:
# Example 2 - breaking (to illustrate when it breaks)
a = np.zeros((10, 2))
b = a.T

In [40]:
c = b.shape(20) 
# can't shape an array without making a copy of it

TypeError: 'tuple' object is not callable

In [50]:
c = b.view()
c.shape = (20)

AttributeError: Incompatible shape for in-place modification. Use `.reshape()` to make a copy with the desired shape.

In [48]:
a.reshape(6)

array([0, 1, 2, 3, 4, 5])

In [46]:
a = np.arange(6).reshape((3, 2))

It is not always possible to change the shape of an array without copying the data. reshape allows making a copy with the desired shape.

In [51]:
# Example 3 - Working
np.reshape(a, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
np.reshape(np.ravel(a), (2, 3))
# ravel is like 'flatten'

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
np.reshape(a, (2, 3), order='F')
# Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

Ravel ==> flattens the array
order || 'F' ==> Fortran like ordering, as opposed to 'C' like ordering.

In [55]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "prashanth-k-narasimhan/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations


'https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations'

## Function 3 - np.extract

Like Filters but with ndarrays.

In [59]:
# Example 1 - working
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
condition = np.mod(arr, 3)==0
condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [61]:
np.extract(condition, arr)

array([0, 3, 6, 9])

Pass a condition which returns a boolean, which filters the array passed.

In [70]:
# Example 2 - working
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
cond=np.eye(3)

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.extract(cond,arr)

array([0, 4, 8])

Explanation about example

In [76]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
cond1=np.eye(4)# (4,4)
cond1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
np.extract(cond1,arr) 
# the number of elements should match with the number of elements in arr

IndexError: index 15 is out of bounds for axis 0 with size 12

In [80]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "prashanth-k-narasimhan/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations


'https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations'

## Function 4 - np.array_split

Add some explanations

In [81]:
# Example 1 - working
list = [1,2,3,4,5]
arr3 = np.asarray(list)
arr3

array([1, 2, 3, 4, 5])

In [82]:
np.array_split(arr3,3)

[array([1, 2]), array([3, 4]), array([5])]

Splits the array to 3 sub array

In [87]:
# Example 2 - working
arr4 = np.random.randint(0,10,[4,4])
arr4

array([[8, 8, 2, 6],
       [5, 4, 9, 0],
       [4, 2, 5, 4],
       [0, 9, 7, 5]])

In [92]:
arr5 = np.array_split(arr4, [1,3])
arr5

[array([[8, 8, 2, 6]]),
 array([[5, 4, 9, 0],
        [4, 2, 5, 4]]),
 array([[0, 9, 7, 5]])]

In [94]:
## If you give an array or list as second argument you basically give the indices (before) which to 'cut'

In [99]:
np.array_split(arr4, [1], axis=1)

[array([[8],
        [5],
        [4],
        [0]]),
 array([[8, 2, 6],
        [4, 9, 0],
        [2, 5, 4],
        [9, 7, 5]])]

 If you give an array or list as second argument you basically give the indices (before) which to 'cut'

In [118]:
# Example 3 - breaking (to illustrate when it breaks)
arr6 = np.full((4,4),7)
np.array_split(arr6, 2, 2)

IndexError: tuple index out of range

Axis 2 in the array it raises the index error as this array doesn't have more than 1 axis. 

In [119]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "prashanth-k-narasimhan/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations


'https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations'

## Function 5 - numpy.stack

Join a sequence of arrays along a new axis.

In [152]:
# Example 1 - working
arrays = np.array([[[ 5,  4,  8,  8],
               [ 6, 16, 12,  7],
               [ 7, 43, 65,  9]],
               [[ 5,  4,  8,  8],
               [ 6, 16, 12,  7],
               [ 7, 43, 65,  9]]])
arrays.shape

(2, 3, 4)

In [153]:
np.stack(arrays, axis=0).shape

(2, 3, 4)

In [154]:
np.stack(arrays, axis=1).shape

(3, 2, 4)

In [155]:
np.stack(arrays, axis=2).shape

(3, 4, 2)

The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

In [156]:
# Example 2 - working
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b), axis = -1)

array([[1, 2],
       [2, 3],
       [3, 4]])

axis=-1 it will be the last dimension

In [159]:
# Example 3 - breaking (to illustrate when it breaks)
array1 = np.array([[[ 5,  4,  8,  8],
               [ 6, 16, 12,  7],
               [ 7, 43, 65,  9]]])
array1.shape

(1, 3, 4)

In [161]:
array2 = np.array([[[ 5,  4,  8],
               [ 6, 16, 12],
               [ 7, 43, 65]]])
array2

array([[[ 5,  4,  8],
        [ 6, 16, 12],
        [ 7, 43, 65]]])

In [162]:
np.stack((array1, array2), axis = -1)

ValueError: all input arrays must have the same shape

all input arrays must have the same shape

Join a sequence of arrays along a new axis.

In [163]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "prashanth-k-narasimhan/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations


'https://jovian.ml/prashanth-k-narasimhan/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
